# Generated by Django 3.2.9 on 2021-12-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='dateofjoin',
            new_name='date_of_join',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='employid',
            new_name='employ_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
