# Generated by Django 3.2.9 on 2021-12-06 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employ', '0002_auto_20211205_0923'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='employid',
        ),
    ]
